###

# curl --location --request PUT 'http://localhost:8080/api/exam/1'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "name":"измененный первый тест",
#    "questions":[
#        {
#        "text":"Назовите первого президента АЛЖИРА",
#        "answers":{
#            "1":"Путин",
#            "2":"Медведев",
#            "3":"Ельцин",
#            "4":"Горбачев"
#        },
#        "rightAnswer":[3]
#        },
#        {
#        "text":"Назовите количество дней в неделе",
#        "answers":{
#            "1":"2",
#            "2":"3",
#            "3":"4",
#            "4":"7"
#        },
#        "rightAnswer":[7]
#        },
#        {
#        "text":"Назовите зимние месяцы",
#        "answers":{
#            "1":"январь",
#            "2":"июнь",
#            "3":"декабрь",
#            "4":"ферваль"
#        },
#        "rightAnswer":[1,3,4]
#        }
#    ]
#}'
PUT http://localhost:8080/api/exam/1
Content-Type: application/json

{
  "name": "измененный первый тест",
  "questions": [
    {
      "text": "Назовите первого президента АЛЖИРА",
      "answers": {
        "1": "Путин",
        "2": "Медведев",
        "3": "Ельцин",
        "4": "Горбачев"
      },
      "rightAnswer": [
        3
      ]
    },
    {
      "text": "Назовите количество дней в неделе",
      "answers": {
        "1": "2",
        "2": "3",
        "3": "4",
        "4": "7"
      },
      "rightAnswer": [
        7
      ]
    },
    {
      "text": "Назовите зимние месяцы",
      "answers": {
        "1": "январь",
        "2": "июнь",
        "3": "декабрь",
        "4": "ферваль"
      },
      "rightAnswer": [
        1,
        3,
        4
      ]
    }
  ]
}

###

