###

# curl --location --request POST 'http://localhost:8080/api/attempt/pass/1'
#--header 'Content-Type: application/json'
#--data-raw '{"answers":[[3],[7],[1,3,4]]}'
POST http://localhost:8080/api/attempt/pass/1
Content-Type: application/json

{
  "answers": [
    [
      3
    ],
    [
      7
    ],
    [
      1,
      3,
      4
    ]
  ]
}

###

